import routerx from "express-promise-router";
import categoriaController from "../controllers/CategoriaController";
import auth from "../middlewares/auth";
const router = routerx();
router.post("/add", categoriaController.add);
router.get("/query", categoriaController.query);
router.get("/list", categoriaController.list);
router.put("/update", categoriaController.update);
router.delete("/remove", categoriaController.remove);
router.put("/activate", categoriaController.activate);
router.put("/desactivate", categoriaController.desactivate);
// router.post("/add", auth.verifyAlmacenero, categoriaController.add);
// router.get("/query", auth.verifyAlmacenero, categoriaController.query);
// router.get("/list", auth.verifyAlmacenero, categoriaController.list);
// router.put("/update", auth.verifyAlmacenero,categoriaController.update);
// router.delete("/remove", auth.verifyAlmacenero, categoriaController.remove);
// router.put("/activate", auth.verifyAlmacenero, categoriaController.activate);
// router.put("/desactivate", auth.verifyAlmacenero, categoriaController.desactivate);
export default router;
